name: Meerkat
version: "1.5.0"
description: A streamlined and beautiful comment system for your Statamic site.
url: https://stillat.com/projects/meerkat
developer: Johnathon Koster
developer_url: stillat.com