name: Meerkat
version: "1.5.74"
description: A streamlined and beautiful comment system for your Statamic site.
url: https://stillat.com/meerkat
developer: Johnathon Koster
developer_url: https://stillat.com/meerkat
commercial: true